spring:
  datasource:
    url: "jdbc:sqlserver://35.222.89.234:1433;database=tempdb"
    password: "G8E6MhM6oCjtR&"
    username: "ms3"
  jackson:
    mapper:
      accept-case-insensitive-enums: true
      allow-coercion-of-scalars: false
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: init-db.sql
